POST http://localhost:3000/api/insert
Content-Type: application/json

{
    "type_sensor":"test",
    "name_sensor":"test463",
    "value_sensor": "70.5"
}

######################################################
#Sensor de Umidade
PUT http://localhost:3000/api/update/18
Content-Type: application/json

{
    "type_sensor":"umidade",
    "name_sensor":"Sensor de Umidade",
    "value_sensor": "90"
}

######################################################
#Sensor de Temperatura
PUT http://localhost:3000/api/update/17
Content-Type: application/json

{
    "type_sensor":"temperatura",
    "name_sensor":"Sensor de Temperatura",
    "value_sensor": "20"
}


######################################################
GET http://localhost:3000/api/getSingle/15

######################################################

GET http://localhost:3000/api/getAll